// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('ngDashboard').directive('counter', [
    '$timeout', function($timeout) {
      return {
        restrict: 'EA',
        scope: {
          data: '='
        },
        template: "<div class='panel panel-warning wid-height-{{data.Size[1]}}'> <div class='panel-heading'> <h3 class='panel-title'>{{data.Title}}</h3> </div> <div class='panel-body'> <h2>{{LastNumber}}<h2> </div> </div>",
        link: function(scope, elm, attr) {
          var Count;
          scope.LastNumber = scope.data.Data.CountFrom;
          Count = function() {
            scope.LastNumber += scope.data.Data.Add;
            $timeout(Count, scope.data.Data.timeout);
          };
          Count();
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=counter.js.map
