// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('ngDashboard', []).directive('dashboard', [
    '$compile', function($compile) {
      return {
        scope: {
          widgetList: '=',
          removeButton: '='
        },
        replace: false,
        restrict: 'EA',
        template: "<div ng-repeat='data in widgetList' class='{{prepareWidth(data)}} widget-container'> <em ng-show='removeButton' class='widget-btn glyphicon glyphicon-remove' ng-click='removeWidget($index)'></em> <div widget remove-button='removeButton' data='data'></div> </div>",
        controller: function($scope) {},
        link: function($scope, elm, attr) {
          $scope.prepareWidth = function(data) {
            return 'col-md-' + data.Size[0];
          };
          return $scope.removeWidget = function(pos) {
            $scope.widgetList.splice(pos, 1);
          };
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=dashboard.js.map
