// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('ngDashboard').directive('hello', [
    '$timeout', function($timeout) {
      return {
        restrict: 'EA',
        scope: {
          data: '='
        },
        template: "<div class='panel panel-warning wid-height-{{data.Size[1]}}'> <div class='panel-heading'> <h3 class='panel-title'>{{data.Title}}</h3> </div> <div class='panel-body'> <h2>Hello World!<h2> </div> </div>",
        link: function(scope, elm, attr) {}
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=hello.js.map
